version: '2'
services:
  app:
    build: .
    container_name: docker-nativescript
    image: docker-nativescript:0.0.1
    privileged: true
    ports:
      - 5901:5901
      - 6901:6901
    volumes:
      - /dev/shm:/dev/shm
      - /home/srghma/projects/nativescript-preact-template/:/app
    working_dir: /app
    environment:
      VNC_RESOLUTION: 1920x1080
      VNC_PW: ""
