version: '2'
services:
  app:
    build: .
    container_name: docker-nativescript
    image: docker-nativescript:0.0.2
    privileged: true
    ports:
      - 5901:5901
      - 6901:6901
    volumes:
      # - /dev/shm:/dev/shm
      - ./app:/app
      # - /home/srghma/projects/purescript-halogen-nextjs/:/app
      # - /home/srghma/projects/cordova-react-starter/:/app
      # - /home/srghma/projects/nativescript-preact-template/:/nativescript-preact-template
      - /home/srghma:/home/srghma
    working_dir: /app
    environment:
      VNC_RESOLUTION: 1920x1080
      VNC_PW: ""
